# Streamlit Secrets for Dashboard LEAP
# Gemini API Key
GEMINI_API_KEY = "AIzaSyACqc3yDCHaJW7J5SVmhSF9Mx8Pg2q0FZM"

# Spreadsheet URL langsung, lebih mudah daripada memasukkan ID saja
spreadsheet_url = "https://docs.google.com/spreadsheets/d/1sSWGdxZe06az_D2sotlj8Z6Hc0a5AY-h0TYJ8DiMN4E/edit?usp=sharing"

project_id = "dashboard-leap"
sheet_names = ["DATA_MASTER", "DATA_ABSENSI", "DATA_NILAI", "DATA_OVERVIEW"]

[gcp_service_account_json]
type = "service_account"
project_id = "dashboard-leap"
private_key_id = "58c55e859e3268b275c6b464c9ba6dedecc32150"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDnrc+ivxpfGI/k
rurB1IIiZXT2BMQAOo6SGsOVgdBU8RrGScgf/eefHzRnWK/VoLDWqlQgW4j0EAi0
8PLgwFsGAvLFxbTxRxaexl6WjlK0e5RLSpYsJfbAWRx69c+veVT24NpgJeduPJgs
1wwzSPbxjmAz9p8DjVVepyZhPjiR4SaY2GS/oMrUh/quH03FDkwzkbk3jCVNewKo
QqCVsLjaak+OJCwanOWY43v0i/1IZqWZfztmOdHxe4UsOjMvAMyND7vxx4SswQjm
Wk0x3ewoQ6ioP9b/gmimM0evuHgc+stQV1g7URK1A//aljexdxT5N7Kh/jVp1/U+
dQ3S0oFzAgMBAAECggEADxWO/k6o/eYQgFgvKr2WV3z5l4cJ5+XoIHUjpNlV4iHs
l1p4cDTM3txeQhhRInya5u8iGRU8nn9owbcqaR29D3AjtGLB/C+ftmi+Adl0YxHk
vt41VtyF61Ih+5ODmS4yLPzI2xe8sL27PrglsDUg9utJMjjtc4LBOy9w3UX60uyR
KPfX4RL+2PWWc3ZB3QOeprL3aRU0LTbG0v3dr9+JcaIfdOK/eVRKd5182mI9/873
EbCKN3M+GPVtIwgOCga+1xsHV8vSBCwrZ+xmUpHqagJR9uWsrJgBzRH/dwADNwFF
6vxjgyWK+VdSguxSR7TNVdaZvgFBZMl5mmMmMucaaQKBgQD5ZeE+R7LDRD65xDzJ
wwuWw22eXGqWSpiiNPd83yppPdW+iKwbFXyZXCc1TsYYlyvbmE4nuqWPcjeoYw2i
nR/ObQro7ugxOV6ecLwGuATa9UWCaX6T7wmZuFbz01vNVHjddQXh/vDJOMFd+Rcc
G2McbvSt+9IbryVAKxmM0F8fBwKBgQDtz9pcltW8c8MjsWMBj89+Kcoa+ReGG118
H0I4L+G5jZuFQwMN1eyIt9k5wZrp6KreH7FaOa40cjb1LSy9j7tiNMj7Zgjp+rkD
rpDC99LjfL4yK9FtKjqhJeiI1ja8uIT+VwKZHvmgubzaBZBQcMGI6Q7oS4T9WVVk
JnNoKxwDNQKBgBfiDcPtEc1pR6h6hme76ewyItk7eGmUEzHVaK3ooSMa7NEmPXUK
hbgZ/xc3x/iq4WRSHYnocdpe0b2qXq/n5BfckWLlHg84szrxCNCL5sshGdr3R0vb
ZEv4PztyTiRHpptujXWq+FwMt1fMds4WQVODvKK8rs4/441Vk0jM248ZAoGBAMTZ
EH8ju7hKenTJGJLqX26nWMwK9BXmAPQFS+MGf2oAdYNRfO2u7iQdSoosX/bOyOEk
isGMjU6MXEGGK0qd9xXLa7HtO+OxzgPmM52vVblIQId3Ddu24OETZ/AcoSKF+lAt
5dCpeyg3lsNBZ7uuGgUiJVzTZjnwAGbuDQlk5cMhAoGBAKNhy0lVZ3/L8slx3bhX
HFUjRoD0WF5eHE0hEfrsvt/2c0rOeItkkRs6cs+JZo9y0HwjHLBfRWBBeCF00V7M
WtAhs7HKjO6lL2vBlMMGAH2cb1KnaMXJNxShGEm7ntWxvzsaq+rSZk7JxOQJXgH7
XawxNXQ/Hl128/2/DuTk4S6X
-----END PRIVATE KEY-----
"""
client_email = "dashboard-leap@dashboard-leap.iam.gserviceaccount.com"
client_id = "115544481699174315742"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dashboard-leap%40dashboard-leap.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
